name: tests

on: [push, pull_request]

env:
  PHP_CS_FIXER_IGNORE_ENV: true

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']
        laravel: [9, 10]
        exclude:
          - php: 8.0
            laravel: 10
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath
          tools: phpize
          coverage: none
      - name: Install Dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Run Cs Fixer
        run: |
          ./vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose --show-progress=dots
      - name: Run Analyse
        run: |
          composer analyse src
      # - name: Run Test Cases
      #   run: |
      #     composer test